
export default [

    {
        // toefl main general description 
        desc: `Soon technology will provide smart cars: cars that virtually drive themselves. A computer in the car determines the speed and route to the desired destination. The computer is in continuous contact with a global positioning system and other technologies that will provide extremely accurate information about the location of the car, other cars on the road, congestion, accidents, and so forth. The human driver will be little more than a passenger. Smart cars promise to make driving safer, quicker, and less expensive.
        First of all, smart cars will prevent many accidents, thereby saving lives. The cars will be equipped with a variety of sensors that very accurately detect cars and other obstacles in their path, and they will have automatic programs that control braking and turning to avoid collisions. Given the hundreds of accidents that occur on highways daily, it is clear that humans do a poor job of avoiding accidents and that computer control would be a great improvement.
        Second, with the wide use of smart cars, traffic problems will practically disappear. These computer-controlled cars can follow each other closely, even at high speeds. This ability will result in increased highway speeds. Today commuting by car can take hours a day. So the increased speed of smart cars will be a great benefit, welcomed by the many people who commute by car.
        Finally, smart cars will bring a reduction in the costs of driving. Because smart cars are programmed to drive the most direct routes, car owners will have to spend less money on repairs and replacement parts. Expensive items such as brakes, tires, and transmissions will last much longer in smart cars than in other cars.`
    },
    {
        // reading general description

        desc: `Soon technology will provide smart cars: cars that virtually drive themselves. A computer in the car determines the speed and route to the desired destination. The computer is in continuous contact with a global positioning system and other technologies that will provide extremely accurate information about the location of the car, other cars on the road, congestion, accidents, and so forth. The human driver will be little more than a passenger. Smart cars promise to make driving safer, quicker, and less expensive.
        First of all, smart cars will prevent many accidents, thereby saving lives. The cars will be equipped with a variety of sensors that very accurately detect cars and other obstacles in their path, and they will have automatic programs that control braking and turning to avoid collisions. Given the hundreds of accidents that occur on highways daily, it is clear that humans do a poor job of avoiding accidents and that computer control would be a great improvement.
        Second, with the wide use of smart cars, traffic problems will practically disappear. These computer-controlled cars can follow each other closely, even at high speeds. This ability will result in increased highway speeds. Today commuting by car can take hours a day. So the increased speed of smart cars will be a great benefit, welcomed by the many people who commute by car.
        Finally, smart cars will bring a reduction in the costs of driving. Because smart cars are programmed to drive the most direct routes, car owners will have to spend less money on repairs and replacement parts. Expensive items such as brakes, tires, and transmissions will last much longer in smart cars than in other cars.`
    },
    {
        // listening general description

        desc: `Soon technology will provide smart cars: cars that virtually drive themselves. A computer in the car determines the speed and route to the desired destination. The computer is in continuous contact with a global positioning system and other technologies that will provide extremely accurate information about the location of the car, other cars on the road, congestion, accidents, and so forth. The human driver will be little more than a passenger. Smart cars promise to make driving safer, quicker, and less expensive.
        First of all, smart cars will prevent many accidents, thereby saving lives. The cars will be equipped with a variety of sensors that very accurately detect cars and other obstacles in their path, and they will have automatic programs that control braking and turning to avoid collisions. Given the hundreds of accidents that occur on highways daily, it is clear that humans do a poor job of avoiding accidents and that computer control would be a great improvement.
        Second, with the wide use of smart cars, traffic problems will practically disappear. These computer-controlled cars can follow each other closely, even at high speeds. This ability will result in increased highway speeds. Today commuting by car can take hours a day. So the increased speed of smart cars will be a great benefit, welcomed by the many people who commute by car.
        Finally, smart cars will bring a reduction in the costs of driving. Because smart cars are programmed to drive the most direct routes, car owners will have to spend less money on repairs and replacement parts. Expensive items such as brakes, tires, and transmissions will last much longer in smart cars than in other cars.`
    },
    {
        // writing general description

        desc: `Soon technology will provide smart cars: cars that virtually drive themselves. A computer in the car determines the speed and route to the desired destination. The computer is in continuous contact with a global positioning system and other technologies that will provide extremely accurate information about the location of the car, other cars on the road, congestion, accidents, and so forth. The human driver will be little more than a passenger. Smart cars promise to make driving safer, quicker, and less expensive.
        First of all, smart cars will prevent many accidents, thereby saving lives. The cars will be equipped with a variety of sensors that very accurately detect cars and other obstacles in their path, and they will have automatic programs that control braking and turning to avoid collisions. Given the hundreds of accidents that occur on highways daily, it is clear that humans do a poor job of avoiding accidents and that computer control would be a great improvement.
        Second, with the wide use of smart cars, traffic problems will practically disappear. These computer-controlled cars can follow each other closely, even at high speeds. This ability will result in increased highway speeds. Today commuting by car can take hours a day. So the increased speed of smart cars will be a great benefit, welcomed by the many people who commute by car.
        Finally, smart cars will bring a reduction in the costs of driving. Because smart cars are programmed to drive the most direct routes, car owners will have to spend less money on repairs and replacement parts. Expensive items such as brakes, tires, and transmissions will last much longer in smart cars than in other cars.`
    },
    {
        // speaking general description

        desc: `Soon technology will provide smart cars: cars that virtually drive themselves. A computer in the car determines the speed and route to the desired destination. The computer is in continuous contact with a global positioning system and other technologies that will provide extremely accurate information about the location of the car, other cars on the road, congestion, accidents, and so forth. The human driver will be little more than a passenger. Smart cars promise to make driving safer, quicker, and less expensive.
        First of all, smart cars will prevent many accidents, thereby saving lives. The cars will be equipped with a variety of sensors that very accurately detect cars and other obstacles in their path, and they will have automatic programs that control braking and turning to avoid collisions. Given the hundreds of accidents that occur on highways daily, it is clear that humans do a poor job of avoiding accidents and that computer control would be a great improvement.
        Second, with the wide use of smart cars, traffic problems will practically disappear. These computer-controlled cars can follow each other closely, even at high speeds. This ability will result in increased highway speeds. Today commuting by car can take hours a day. So the increased speed of smart cars will be a great benefit, welcomed by the many people who commute by car.
        Finally, smart cars will bring a reduction in the costs of driving. Because smart cars are programmed to drive the most direct routes, car owners will have to spend less money on repairs and replacement parts. Expensive items such as brakes, tires, and transmissions will last much longer in smart cars than in other cars.`
    }

]